apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-transfer-deployment
spec:
  replicas: 1  # Number of pods to run
  selector:
    matchLabels:
      app: data-transfer
  template:
    metadata:
      labels:
        app: data-transfer
    spec:
      containers:
      - name: data-transfer-container
        image: isaacblekhman14/testrepo:v1
       